### ISSUE TITLE
[CSS] fix indentation

### ISSUE THREAD

**Issue by Idrinth** [SPIRITORBS/portfolio-HTML-CSS-JS#8]
You are mixing indentation levels in your css file:

```css
.example,
 .test {
color: black;
}
```
should be
```css
.example,
.test {
  color: black;
}
```
according to usual standards. This makes reading easier by providing more hints about the depth of selections and reducing the left-right movement required.
